name: Deploy Contract to Unnamed Network

on:
  push:
    branches: [ main ]

jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    permissions:
      write-all: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Contract
        uses: YBadiss/deploy-contract@v2
        with:
          contract-name: 'HelloWorld.sol'
          parent-dir: './contracts'
          deployer-pk: ${{ secrets.PRIVATE_KEY }}
          chain-id: '80002'
          rpc-url: 'https://rpc-amoy.polygon.technology/'
          verify: false
          etherscan-url: ''
          etherscan-api-key: ${{ secrets.ETHERSCAN_API_KEY }}