
name: Backup to WALRUS
on: [push]
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install -g oswald
      - run: oswald backupFiles
    env:
      CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
